//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     Runtime Version:4.0.30319.235
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace SSHTunnelManager.Properties {
    using System;
    
    
    /// <summary>
    ///   A strongly-typed resource class, for looking up localized strings, etc.
    /// </summary>
    // This class was auto-generated by the StronglyTypedResourceBuilder
    // class via a tool like ResGen or Visual Studio.
    // To add or remove a member, edit your .ResX file then rerun ResGen
    // with the /str option, or rebuild your VS project.
    [global::System.CodeDom.Compiler.GeneratedCodeAttribute("System.Resources.Tools.StronglyTypedResourceBuilder", "4.0.0.0")]
    [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
    [global::System.Runtime.CompilerServices.CompilerGeneratedAttribute()]
    internal class Resources {
        
        private static global::System.Resources.ResourceManager resourceMan;
        
        private static global::System.Globalization.CultureInfo resourceCulture;
        
        [global::System.Diagnostics.CodeAnalysis.SuppressMessageAttribute("Microsoft.Performance", "CA1811:AvoidUncalledPrivateCode")]
        internal Resources() {
        }
        
        /// <summary>
        ///   Returns the cached ResourceManager instance used by this class.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        internal static global::System.Resources.ResourceManager ResourceManager {
            get {
                if (object.ReferenceEquals(resourceMan, null)) {
                    global::System.Resources.ResourceManager temp = new global::System.Resources.ResourceManager("SSHTunnelManager.Properties.Resources", typeof(Resources).Assembly);
                    resourceMan = temp;
                }
                return resourceMan;
            }
        }
        
        /// <summary>
        ///   Overrides the current thread's CurrentUICulture property for all
        ///   resource lookups using this strongly typed resource class.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        internal static global::System.Globalization.CultureInfo Culture {
            get {
                return resourceCulture;
            }
            set {
                resourceCulture = value;
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Cannot add an external item to the view. Use AddNew() or add to source list instead..
        /// </summary>
        internal static string CannotAddItem {
            get {
                return ResourceManager.GetString("CannotAddItem", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Cannot add a new item due to no object being provided in the AddingNew event and a lack of default public constructor..
        /// </summary>
        internal static string CannotAddNewItem {
            get {
                return ResourceManager.GetString("CannotAddNewItem", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Cannot add a new item when NewItemsList is null..
        /// </summary>
        internal static string CannotAddWhenNewItemsListNull {
            get {
                return ResourceManager.GetString("CannotAddWhenNewItemsListNull", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Cannot clear this view..
        /// </summary>
        internal static string CannotClearView {
            get {
                return ResourceManager.GetString("CannotClearView", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Cannot insert an external item into this collection..
        /// </summary>
        internal static string CannotInsertItem {
            get {
                return ResourceManager.GetString("CannotInsertItem", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Cannot set an item in the view..
        /// </summary>
        internal static string CannotSetItem {
            get {
                return ResourceManager.GetString("CannotSetItem", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Invalid tunnel type..
        /// </summary>
        internal static string ConsoleTools_Error_InvalidTunnelType {
            get {
                return ResourceManager.GetString("ConsoleTools_Error_InvalidTunnelType", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Windows Registry Editor Version 5.00
        ///
        ///[HKEY_CURRENT_USER\Software\SimonTatham\PuTTY\Sessions\_ptm_preset_]
        ///&quot;Present&quot;=dword:00000001
        ///&quot;HostName&quot;=&quot;&quot;
        ///&quot;LogFileName&quot;=&quot;putty.log&quot;
        ///&quot;LogType&quot;=dword:00000000
        ///&quot;LogFileClash&quot;=dword:ffffffff
        ///&quot;LogFlush&quot;=dword:00000001
        ///&quot;SSHLogOmitPasswords&quot;=dword:00000001
        ///&quot;SSHLogOmitData&quot;=dword:00000000
        ///&quot;Protocol&quot;=&quot;ssh&quot;
        ///&quot;PortNumber&quot;=dword:00000016
        ///&quot;CloseOnExit&quot;=dword:00000001
        ///&quot;WarnOnClose&quot;=dword:00000001
        ///&quot;PingInterval&quot;=dword:00000000
        ///&quot;PingIntervalSecs&quot;=dword:00000000
        ///&quot;TCPNo [rest of string was truncated]&quot;;.
        /// </summary>
        internal static string defaultPuttyProfile {
            get {
                return ResourceManager.GetString("defaultPuttyProfile", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Program will be started without PuTTY profile features..
        /// </summary>
        internal static string HostsManager_Error_LoadPuttyProfileError {
            get {
                return ResourceManager.GetString("HostsManager_Error_LoadPuttyProfileError", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to includeDelegate cannot be null..
        /// </summary>
        internal static string IncludeDelegateCannotBeNull {
            get {
                return ResourceManager.GetString("IncludeDelegateCannotBeNull", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Item in list is not of type {0}..
        /// </summary>
        internal static string InvalidListItemType {
            get {
                return ResourceManager.GetString("InvalidListItemType", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Source list does not implement IList..
        /// </summary>
        internal static string InvalidSourceList {
            get {
                return ResourceManager.GetString("InvalidSourceList", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Item was not of type {0}..
        /// </summary>
        internal static string ItemTypeIncorrect {
            get {
                return ResourceManager.GetString("ItemTypeIncorrect", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Error while retrieving log4net appender {0}. Appender not found..
        /// </summary>
        internal static string Logger_Error_GetAppender {
            get {
                return ResourceManager.GetString("Logger_Error_GetAppender", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Error while retrieving log4net hierarchy..
        /// </summary>
        internal static string Logger_Error_GetRepository {
            get {
                return ResourceManager.GetString("Logger_Error_GetRepository", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to (no filter).
        /// </summary>
        internal static string NoFilter {
            get {
                return ResourceManager.GetString("NoFilter", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Object cannot be null..
        /// </summary>
        internal static string ObjectCannotBeNull {
            get {
                return ResourceManager.GetString("ObjectCannotBeNull", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to (predicate filter).
        /// </summary>
        internal static string PredicateFilter {
            get {
                return ResourceManager.GetString("PredicateFilter", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Property {0} does not exist in type {1}..
        /// </summary>
        internal static string PropertyNotFound {
            get {
                return ResourceManager.GetString("PropertyNotFound", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Invalid username.
        /// </summary>
        internal static string PuttyLink_Error_InvalidUsername {
            get {
                return ResourceManager.GetString("PuttyLink_Error_InvalidUsername", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Link already started..
        /// </summary>
        internal static string PuttyLink_Error_LinkAlreadyStarted {
            get {
                return ResourceManager.GetString("PuttyLink_Error_LinkAlreadyStarted", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Restarting after connection loss....
        /// </summary>
        internal static string PuttyLink_Status_Restarting {
            get {
                return ResourceManager.GetString("PuttyLink_Status_Restarting", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Started.
        /// </summary>
        internal static string PuttyLink_Status_Started {
            get {
                return ResourceManager.GetString("PuttyLink_Status_Started", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Started with warnings.
        /// </summary>
        internal static string PuttyLink_Status_StartedWithWarnings {
            get {
                return ResourceManager.GetString("PuttyLink_Status_StartedWithWarnings", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Starting....
        /// </summary>
        internal static string PuttyLink_Status_Starting {
            get {
                return ResourceManager.GetString("PuttyLink_Status_Starting", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Stopped.
        /// </summary>
        internal static string PuttyLink_Status_Stopped {
            get {
                return ResourceManager.GetString("PuttyLink_Status_Stopped", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Waiting {0} seconds before restart....
        /// </summary>
        internal static string PuttyLink_Status_Waiting {
            get {
                return ResourceManager.GetString("PuttyLink_Status_Waiting", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Source list already added to the view..
        /// </summary>
        internal static string SourceListAlreadyAdded {
            get {
                return ResourceManager.GetString("SourceListAlreadyAdded", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Source list is not in the view..
        /// </summary>
        internal static string SourceListNotFound {
            get {
                return ResourceManager.GetString("SourceListNotFound", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to SourceLists cannot be null..
        /// </summary>
        internal static string SourceListsNull {
            get {
                return ResourceManager.GetString("SourceListsNull", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Synchronized access to the view is not supported..
        /// </summary>
        internal static string SyncAccessNotSupported {
            get {
                return ResourceManager.GetString("SyncAccessNotSupported", resourceCulture);
            }
        }
    }
}
