//------------------------------------------------------------------------------
// <auto-generated>
//     Ce code a été généré par un outil.
//     Version du runtime :4.0.30319.42000
//
//     Les modifications apportées à ce fichier peuvent provoquer un comportement incorrect et seront perdues si
//     le code est régénéré.
// </auto-generated>
//------------------------------------------------------------------------------

namespace SSHTunnelManagerGUI.Properties {
    using System;
    
    
    /// <summary>
    ///   Une classe de ressource fortement typée destinée, entre autres, à la consultation des chaînes localisées.
    /// </summary>
    // Cette classe a été générée automatiquement par la classe StronglyTypedResourceBuilder
    // à l'aide d'un outil, tel que ResGen ou Visual Studio.
    // Pour ajouter ou supprimer un membre, modifiez votre fichier .ResX, puis réexécutez ResGen
    // avec l'option /str ou régénérez votre projet VS.
    [global::System.CodeDom.Compiler.GeneratedCodeAttribute("System.Resources.Tools.StronglyTypedResourceBuilder", "4.0.0.0")]
    [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
    [global::System.Runtime.CompilerServices.CompilerGeneratedAttribute()]
    internal class Resources {
        
        private static global::System.Resources.ResourceManager resourceMan;
        
        private static global::System.Globalization.CultureInfo resourceCulture;
        
        [global::System.Diagnostics.CodeAnalysis.SuppressMessageAttribute("Microsoft.Performance", "CA1811:AvoidUncalledPrivateCode")]
        internal Resources() {
        }
        
        /// <summary>
        ///   Retourne l'instance ResourceManager mise en cache utilisée par cette classe.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        internal static global::System.Resources.ResourceManager ResourceManager {
            get {
                if (object.ReferenceEquals(resourceMan, null)) {
                    global::System.Resources.ResourceManager temp = new global::System.Resources.ResourceManager("SSHTunnelManagerGUI.Properties.Resources", typeof(Resources).Assembly);
                    resourceMan = temp;
                }
                return resourceMan;
            }
        }
        
        /// <summary>
        ///   Remplace la propriété CurrentUICulture du thread actuel pour toutes
        ///   les recherches de ressources à l'aide de cette classe de ressource fortement typée.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        internal static global::System.Globalization.CultureInfo Culture {
            get {
                return resourceCulture;
            }
            set {
                resourceCulture = value;
            }
        }
        
        /// <summary>
        ///   Recherche une chaîne localisée semblable à About {0}.
        /// </summary>
        internal static string AboutBox_AboutText {
            get {
                return ResourceManager.GetString("AboutBox_AboutText", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Recherche une chaîne localisée semblable à Version {0}.
        /// </summary>
        internal static string AboutBox_VersionText {
            get {
                return ResourceManager.GetString("AboutBox_VersionText", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Recherche une ressource localisée de type System.Drawing.Bitmap.
        /// </summary>
        internal static System.Drawing.Bitmap arrow_circle_315 {
            get {
                object obj = ResourceManager.GetObject("arrow_circle_315", resourceCulture);
                return ((System.Drawing.Bitmap)(obj));
            }
        }
        
        /// <summary>
        ///   Recherche une ressource localisée de type System.Drawing.Bitmap.
        /// </summary>
        internal static System.Drawing.Bitmap arrow_skip_090 {
            get {
                object obj = ResourceManager.GetObject("arrow_skip_090", resourceCulture);
                return ((System.Drawing.Bitmap)(obj));
            }
        }
        
        /// <summary>
        ///   Recherche une ressource localisée de type System.Drawing.Bitmap.
        /// </summary>
        internal static System.Drawing.Bitmap arrow_skip_270 {
            get {
                object obj = ResourceManager.GetObject("arrow_skip_270", resourceCulture);
                return ((System.Drawing.Bitmap)(obj));
            }
        }
        
        /// <summary>
        ///   Recherche une ressource localisée de type System.Drawing.Bitmap.
        /// </summary>
        internal static System.Drawing.Bitmap brightness {
            get {
                object obj = ResourceManager.GetObject("brightness", resourceCulture);
                return ((System.Drawing.Bitmap)(obj));
            }
        }
        
        /// <summary>
        ///   Recherche une ressource localisée de type System.Drawing.Bitmap.
        /// </summary>
        internal static System.Drawing.Bitmap brightness_small {
            get {
                object obj = ResourceManager.GetObject("brightness_small", resourceCulture);
                return ((System.Drawing.Bitmap)(obj));
            }
        }
        
        /// <summary>
        ///   Recherche une chaîne localisée semblable à Close.
        /// </summary>
        internal static string ButtonText_Close {
            get {
                return ResourceManager.GetString("ButtonText_Close", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Recherche une chaîne localisée semblable à http://creativecommons.org/licenses/by/3.0/.
        /// </summary>
        internal static string CCA3LicensePage {
            get {
                return ResourceManager.GetString("CCA3LicensePage", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Recherche une chaîne localisée semblable à &amp;Edit....
        /// </summary>
        internal static string ContextMenuText_Edit {
            get {
                return ResourceManager.GetString("ContextMenuText_Edit", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Recherche une chaîne localisée semblable à &amp;Remove.
        /// </summary>
        internal static string ContextMenuText_Remove {
            get {
                return ResourceManager.GetString("ContextMenuText_Remove", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Recherche une chaîne localisée semblable à Start.
        /// </summary>
        internal static string ContextMenuText_Start {
            get {
                return ResourceManager.GetString("ContextMenuText_Start", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Recherche une chaîne localisée semblable à Start FileZilla SFTP.
        /// </summary>
        internal static string ContextMenuText_StartFileZilla {
            get {
                return ResourceManager.GetString("ContextMenuText_StartFileZilla", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Recherche une chaîne localisée semblable à Start psftp.
        /// </summary>
        internal static string ContextMenuText_StartPsftp {
            get {
                return ResourceManager.GetString("ContextMenuText_StartPsftp", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Recherche une chaîne localisée semblable à Start PuTTY.
        /// </summary>
        internal static string ContextMenuText_StartPuTTY {
            get {
                return ResourceManager.GetString("ContextMenuText_StartPuTTY", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Recherche une chaîne localisée semblable à Stop.
        /// </summary>
        internal static string ContextMenuText_Stop {
            get {
                return ResourceManager.GetString("ContextMenuText_Stop", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Recherche une ressource localisée de type System.Drawing.Bitmap.
        /// </summary>
        internal static System.Drawing.Bitmap control {
            get {
                object obj = ResourceManager.GetObject("control", resourceCulture);
                return ((System.Drawing.Bitmap)(obj));
            }
        }
        
        /// <summary>
        ///   Recherche une ressource localisée de type System.Drawing.Bitmap.
        /// </summary>
        internal static System.Drawing.Bitmap control_000_small {
            get {
                object obj = ResourceManager.GetObject("control_000_small", resourceCulture);
                return ((System.Drawing.Bitmap)(obj));
            }
        }
        
        /// <summary>
        ///   Recherche une ressource localisée de type System.Drawing.Bitmap.
        /// </summary>
        internal static System.Drawing.Bitmap control_stop_square {
            get {
                object obj = ResourceManager.GetObject("control_stop_square", resourceCulture);
                return ((System.Drawing.Bitmap)(obj));
            }
        }
        
        /// <summary>
        ///   Recherche une ressource localisée de type System.Drawing.Bitmap.
        /// </summary>
        internal static System.Drawing.Bitmap control_stop_square_small {
            get {
                object obj = ResourceManager.GetObject("control_stop_square_small", resourceCulture);
                return ((System.Drawing.Bitmap)(obj));
            }
        }
        
        /// <summary>
        ///   Recherche une ressource localisée de type System.Drawing.Bitmap.
        /// </summary>
        internal static System.Drawing.Bitmap database {
            get {
                object obj = ResourceManager.GetObject("database", resourceCulture);
                return ((System.Drawing.Bitmap)(obj));
            }
        }
        
        /// <summary>
        ///   Recherche une ressource localisée de type System.Drawing.Bitmap.
        /// </summary>
        internal static System.Drawing.Bitmap databases__arrow {
            get {
                object obj = ResourceManager.GetObject("databases__arrow", resourceCulture);
                return ((System.Drawing.Bitmap)(obj));
            }
        }
        
        /// <summary>
        ///   Recherche une ressource localisée de type System.Drawing.Bitmap.
        /// </summary>
        internal static System.Drawing.Bitmap disco {
            get {
                object obj = ResourceManager.GetObject("disco", resourceCulture);
                return ((System.Drawing.Bitmap)(obj));
            }
        }
        
        /// <summary>
        ///   Recherche une ressource localisée de type System.Drawing.Bitmap.
        /// </summary>
        internal static System.Drawing.Bitmap disk {
            get {
                object obj = ResourceManager.GetObject("disk", resourceCulture);
                return ((System.Drawing.Bitmap)(obj));
            }
        }
        
        /// <summary>
        ///   Recherche une ressource localisée de type System.Drawing.Bitmap.
        /// </summary>
        internal static System.Drawing.Bitmap exclamation_small {
            get {
                object obj = ResourceManager.GetObject("exclamation_small", resourceCulture);
                return ((System.Drawing.Bitmap)(obj));
            }
        }
        
        /// <summary>
        ///   Recherche une ressource localisée de type System.Drawing.Bitmap.
        /// </summary>
        internal static System.Drawing.Bitmap filezilla {
            get {
                object obj = ResourceManager.GetObject("filezilla", resourceCulture);
                return ((System.Drawing.Bitmap)(obj));
            }
        }
        
        /// <summary>
        ///   Recherche une chaîne localisée semblable à http://p.yusukekamiyamane.com/.
        /// </summary>
        internal static string FuguePage {
            get {
                return ResourceManager.GetString("FuguePage", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Recherche une ressource localisée de type System.Drawing.Bitmap.
        /// </summary>
        internal static System.Drawing.Bitmap Gear {
            get {
                object obj = ResourceManager.GetObject("Gear", resourceCulture);
                return ((System.Drawing.Bitmap)(obj));
            }
        }
        
        /// <summary>
        ///   Recherche une chaîne localisée semblable à http://www.gnu.org/licenses/gpl.html.
        /// </summary>
        internal static string GNUGPLv3Page {
            get {
                return ResourceManager.GetString("GNUGPLv3Page", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Recherche une ressource localisée de type System.Drawing.Bitmap.
        /// </summary>
        internal static System.Drawing.Bitmap greenCircle {
            get {
                object obj = ResourceManager.GetObject("greenCircle", resourceCulture);
                return ((System.Drawing.Bitmap)(obj));
            }
        }
        
        /// <summary>
        ///   Recherche une chaîne localisée semblable à Add New Host - SSH Tunnel Manager.
        /// </summary>
        internal static string HostDialog_AddNewHostTitle {
            get {
                return ResourceManager.GetString("HostDialog_AddNewHostTitle", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Recherche une chaîne localisée semblable à You might have forgotten to press the &apos;Add&apos; button, add new tunnel into list?.
        /// </summary>
        internal static string HostDialog_AddTunnelButtonReminder {
            get {
                return ResourceManager.GetString("HostDialog_AddTunnelButtonReminder", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Recherche une chaîne localisée semblable à None.
        /// </summary>
        internal static string HostDialog_DependsOnNone {
            get {
                return ResourceManager.GetString("HostDialog_DependsOnNone", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Recherche une chaîne localisée semblable à Edit Host - SSH Tunnel Manager.
        /// </summary>
        internal static string HostDialog_EditHostTitle {
            get {
                return ResourceManager.GetString("HostDialog_EditHostTitle", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Recherche une chaîne localisée semblable à Host property is null..
        /// </summary>
        internal static string HostDialog_HostPropertyIsNull {
            get {
                return ResourceManager.GetString("HostDialog_HostPropertyIsNull", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Recherche une chaîne localisée semblable à Recently added: {0}.
        /// </summary>
        internal static string HostDialog_RecentlyAdded {
            get {
                return ResourceManager.GetString("HostDialog_RecentlyAdded", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Recherche une chaîne localisée semblable à Status {0} not supported..
        /// </summary>
        internal static string HostViewModel_StatusNotSupported {
            get {
                return ResourceManager.GetString("HostViewModel_StatusNotSupported", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Recherche une ressource localisée de type System.Drawing.Bitmap.
        /// </summary>
        internal static System.Drawing.Bitmap icon_16x16_putty {
            get {
                object obj = ResourceManager.GetObject("icon_16x16_putty", resourceCulture);
                return ((System.Drawing.Bitmap)(obj));
            }
        }
        
        /// <summary>
        ///   Recherche une ressource localisée de type System.Drawing.Bitmap.
        /// </summary>
        internal static System.Drawing.Bitmap key__arrow {
            get {
                object obj = ResourceManager.GetObject("key__arrow", resourceCulture);
                return ((System.Drawing.Bitmap)(obj));
            }
        }
        
        /// <summary>
        ///   Recherche une ressource localisée de type System.Drawing.Bitmap.
        /// </summary>
        internal static System.Drawing.Bitmap logo_putty {
            get {
                object obj = ResourceManager.GetObject("logo_putty", resourceCulture);
                return ((System.Drawing.Bitmap)(obj));
            }
        }
        
        /// <summary>
        ///   Recherche une chaîne localisée semblable à Storage was modified, save before closing?.
        /// </summary>
        internal static string MessageBoxText_AskForSaveStorage {
            get {
                return ResourceManager.GetString("MessageBoxText_AskForSaveStorage", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Recherche une chaîne localisée semblable à Are you sure you want to remove host &apos;{0}&apos;?.
        /// </summary>
        internal static string MessageBoxText_RemoveHostAsk {
            get {
                return ResourceManager.GetString("MessageBoxText_RemoveHostAsk", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Recherche une chaîne localisée semblable à Following hosts depends on host &apos;{0}&apos;:{1}{1}{2}{1}{1}Are you sure you want to remove the selected host?.
        /// </summary>
        internal static string MessageBoxText_RemoveHostAsk2 {
            get {
                return ResourceManager.GetString("MessageBoxText_RemoveHostAsk2", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Recherche une chaîne localisée semblable à Some hosts that host &apos;{0}&apos; depends on are down. Start over recursively?.
        /// </summary>
        internal static string MessageBoxText_StartHostRecursively {
            get {
                return ResourceManager.GetString("MessageBoxText_StartHostRecursively", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Recherche une chaîne localisée semblable à http://www.chiark.greenend.org.uk/~sgtatham/putty/licence.html.
        /// </summary>
        internal static string MITLicensePage {
            get {
                return ResourceManager.GetString("MITLicensePage", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Recherche une chaîne localisée semblable à This control is not registered new-password/confirmation control..
        /// </summary>
        internal static string NewPasswordValidatorFunctor_Validate_InvalidControl {
            get {
                return ResourceManager.GetString("NewPasswordValidatorFunctor_Validate_InvalidControl", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Recherche une ressource localisée de type System.Drawing.Bitmap.
        /// </summary>
        internal static System.Drawing.Bitmap orangeCircle {
            get {
                object obj = ResourceManager.GetObject("orangeCircle", resourceCulture);
                return ((System.Drawing.Bitmap)(obj));
            }
        }
        
        /// <summary>
        ///   Recherche une chaîne localisée semblable à https://github.com/intika/ssh-tunnel-manager.
        /// </summary>
        internal static string ProjectPage {
            get {
                return ResourceManager.GetString("ProjectPage", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Recherche une ressource localisée de type System.Drawing.Icon semblable à (Icône).
        /// </summary>
        internal static System.Drawing.Icon psftp {
            get {
                object obj = ResourceManager.GetObject("psftp", resourceCulture);
                return ((System.Drawing.Icon)(obj));
            }
        }
        
        /// <summary>
        ///   Recherche une chaîne localisée semblable à START action for host &apos;{0}&apos; timed out. Terminating actions chain..
        /// </summary>
        internal static string PuttyLink_WaitForStartTimedOut {
            get {
                return ResourceManager.GetString("PuttyLink_WaitForStartTimedOut", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Recherche une chaîne localisée semblable à STOP action for host &apos;{0}&apos; timed out. Terminating actions chain..
        /// </summary>
        internal static string PuttyLink_WaitForStopTimedOut {
            get {
                return ResourceManager.GetString("PuttyLink_WaitForStopTimedOut", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Recherche une ressource localisée de type System.Drawing.Bitmap.
        /// </summary>
        internal static System.Drawing.Bitmap redCircle {
            get {
                object obj = ResourceManager.GetObject("redCircle", resourceCulture);
                return ((System.Drawing.Bitmap)(obj));
            }
        }
        
        /// <summary>
        ///   Recherche une ressource localisée de type System.Drawing.Bitmap.
        /// </summary>
        internal static System.Drawing.Bitmap Remote_desktop_connection_icon16 {
            get {
                object obj = ResourceManager.GetObject("Remote_desktop_connection_icon16", resourceCulture);
                return ((System.Drawing.Bitmap)(obj));
            }
        }
        
        /// <summary>
        ///   Recherche une ressource localisée de type System.Drawing.Bitmap.
        /// </summary>
        internal static System.Drawing.Bitmap server__minus {
            get {
                object obj = ResourceManager.GetObject("server__minus", resourceCulture);
                return ((System.Drawing.Bitmap)(obj));
            }
        }
        
        /// <summary>
        ///   Recherche une ressource localisée de type System.Drawing.Bitmap.
        /// </summary>
        internal static System.Drawing.Bitmap server__pencil {
            get {
                object obj = ResourceManager.GetObject("server__pencil", resourceCulture);
                return ((System.Drawing.Bitmap)(obj));
            }
        }
        
        /// <summary>
        ///   Recherche une ressource localisée de type System.Drawing.Bitmap.
        /// </summary>
        internal static System.Drawing.Bitmap server__plus {
            get {
                object obj = ResourceManager.GetObject("server__plus", resourceCulture);
                return ((System.Drawing.Bitmap)(obj));
            }
        }
        
        /// <summary>
        ///   Recherche une ressource localisée de type System.Drawing.Bitmap.
        /// </summary>
        internal static System.Drawing.Bitmap server_down {
            get {
                object obj = ResourceManager.GetObject("server_down", resourceCulture);
                return ((System.Drawing.Bitmap)(obj));
            }
        }
        
        /// <summary>
        ///   Recherche une ressource localisée de type System.Drawing.Bitmap.
        /// </summary>
        internal static System.Drawing.Bitmap server_up {
            get {
                object obj = ResourceManager.GetObject("server_up", resourceCulture);
                return ((System.Drawing.Bitmap)(obj));
            }
        }
        
        /// <summary>
        ///   Recherche une ressource localisée de type System.Drawing.Bitmap.
        /// </summary>
        internal static System.Drawing.Bitmap server_up_warnings {
            get {
                object obj = ResourceManager.GetObject("server_up_warnings", resourceCulture);
                return ((System.Drawing.Bitmap)(obj));
            }
        }
        
        /// <summary>
        ///   Recherche une ressource localisée de type System.Drawing.Bitmap.
        /// </summary>
        internal static System.Drawing.Bitmap ServerImage {
            get {
                object obj = ResourceManager.GetObject("ServerImage", resourceCulture);
                return ((System.Drawing.Bitmap)(obj));
            }
        }
        
        /// <summary>
        ///   Recherche une ressource localisée de type System.Drawing.Bitmap.
        /// </summary>
        internal static System.Drawing.Bitmap Servers {
            get {
                object obj = ResourceManager.GetObject("Servers", resourceCulture);
                return ((System.Drawing.Bitmap)(obj));
            }
        }
        
        /// <summary>
        ///   Recherche une ressource localisée de type System.Drawing.Bitmap.
        /// </summary>
        internal static System.Drawing.Bitmap servers__minus {
            get {
                object obj = ResourceManager.GetObject("servers__minus", resourceCulture);
                return ((System.Drawing.Bitmap)(obj));
            }
        }
        
        /// <summary>
        ///   Recherche une ressource localisée de type System.Drawing.Icon semblable à (Icône).
        /// </summary>
        internal static System.Drawing.Icon terminal {
            get {
                object obj = ResourceManager.GetObject("terminal", resourceCulture);
                return ((System.Drawing.Icon)(obj));
            }
        }
        
        /// <summary>
        ///   Recherche une ressource localisée de type System.Drawing.Icon semblable à (Icône).
        /// </summary>
        internal static System.Drawing.Icon terminal_green {
            get {
                object obj = ResourceManager.GetObject("terminal_green", resourceCulture);
                return ((System.Drawing.Icon)(obj));
            }
        }
        
        /// <summary>
        ///   Recherche une ressource localisée de type System.Drawing.Icon semblable à (Icône).
        /// </summary>
        internal static System.Drawing.Icon terminal_red {
            get {
                object obj = ResourceManager.GetObject("terminal_red", resourceCulture);
                return ((System.Drawing.Icon)(obj));
            }
        }
        
        /// <summary>
        ///   Recherche une ressource localisée de type System.Drawing.Bitmap.
        /// </summary>
        internal static System.Drawing.Bitmap tick_circle {
            get {
                object obj = ResourceManager.GetObject("tick_circle", resourceCulture);
                return ((System.Drawing.Bitmap)(obj));
            }
        }
        
        /// <summary>
        ///   Recherche une ressource localisée de type System.Drawing.Bitmap.
        /// </summary>
        internal static System.Drawing.Bitmap tick_small_circle {
            get {
                object obj = ResourceManager.GetObject("tick_small_circle", resourceCulture);
                return ((System.Drawing.Bitmap)(obj));
            }
        }
        
        /// <summary>
        ///   Recherche une chaîne localisée semblable à &amp;Exit.
        /// </summary>
        internal static string TrayForm_ContextMenu_Exit {
            get {
                return ResourceManager.GetString("TrayForm_ContextMenu_Exit", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Recherche une chaîne localisée semblable à Hide/show.
        /// </summary>
        internal static string TrayForm_ContextMenu_HideShow {
            get {
                return ResourceManager.GetString("TrayForm_ContextMenu_HideShow", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Recherche une chaîne localisée semblable à {0} has minimized here..
        /// </summary>
        internal static string TrayForm_OnMinimizedText {
            get {
                return ResourceManager.GetString("TrayForm_OnMinimizedText", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Recherche une chaîne localisée semblable à Control has not been set..
        /// </summary>
        internal static string Validator_ValidateControl_ControlHasNotBeenSet {
            get {
                return ResourceManager.GetString("Validator_ValidateControl_ControlHasNotBeenSet", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Recherche une chaîne localisée semblable à File does not exist..
        /// </summary>
        internal static string ValidatorError_FileDoesNotExist {
            get {
                return ResourceManager.GetString("ValidatorError_FileDoesNotExist", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Recherche une chaîne localisée semblable à Alias is used by other host..
        /// </summary>
        internal static string ValidatorError_HostAliasBusy {
            get {
                return ResourceManager.GetString("ValidatorError_HostAliasBusy", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Recherche une chaîne localisée semblable à Invalid hostname.
        /// </summary>
        internal static string ValidatorError_Hostname {
            get {
                return ResourceManager.GetString("ValidatorError_Hostname", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Recherche une chaîne localisée semblable à You need to specify hostname in the form &apos;hostname:port&apos;.
        /// </summary>
        internal static string ValidatorError_HostnameAndPort {
            get {
                return ResourceManager.GetString("ValidatorError_HostnameAndPort", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Recherche une chaîne localisée semblable à Local port is used by other tunnel with host &apos;{0}&apos;..
        /// </summary>
        internal static string ValidatorError_LocalPortBusyAnotherHost {
            get {
                return ResourceManager.GetString("ValidatorError_LocalPortBusyAnotherHost", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Recherche une chaîne localisée semblable à Local port is used by other tunnel of this host..
        /// </summary>
        internal static string ValidatorError_LocalPortBusyThisHost {
            get {
                return ResourceManager.GetString("ValidatorError_LocalPortBusyThisHost", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Recherche une chaîne localisée semblable à Password and confirmation does not match..
        /// </summary>
        internal static string ValidatorError_NewPassword {
            get {
                return ResourceManager.GetString("ValidatorError_NewPassword", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Recherche une chaîne localisée semblable à You need to specify this value..
        /// </summary>
        internal static string ValidatorError_NotNullOrWhitespaces {
            get {
                return ResourceManager.GetString("ValidatorError_NotNullOrWhitespaces", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Recherche une chaîne localisée semblable à The value should be a word without spaces..
        /// </summary>
        internal static string ValidatorError_OnlyOneWord {
            get {
                return ResourceManager.GetString("ValidatorError_OnlyOneWord", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Recherche une chaîne localisée semblable à You need to specify port number as number in range 1-65536.
        /// </summary>
        internal static string ValidatorError_PortNumber {
            get {
                return ResourceManager.GetString("ValidatorError_PortNumber", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Recherche une chaîne localisée semblable à Alias is used by other tunnel..
        /// </summary>
        internal static string ValidatorError_TunnelAliasBusy {
            get {
                return ResourceManager.GetString("ValidatorError_TunnelAliasBusy", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Recherche une chaîne localisée semblable à Destination hostname should be empty for dynamic tunnels..
        /// </summary>
        internal static string ValidatorError_TunnelDstHostnameNotEmpty {
            get {
                return ResourceManager.GetString("ValidatorError_TunnelDstHostnameNotEmpty", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Recherche une chaîne localisée semblable à Hostname should be empty for dynamic tunnels..
        /// </summary>
        internal static string ValidatorError_TunnelHostnameNotEmpty {
            get {
                return ResourceManager.GetString("ValidatorError_TunnelHostnameNotEmpty", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Recherche une ressource localisée de type System.Drawing.Bitmap.
        /// </summary>
        internal static System.Drawing.Bitmap yellowCircle {
            get {
                object obj = ResourceManager.GetObject("yellowCircle", resourceCulture);
                return ((System.Drawing.Bitmap)(obj));
            }
        }
    }
}
