//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     Runtime Version:4.0.30319.235
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace SSHTunnelManagerGUI.Properties {
    using System;
    
    
    /// <summary>
    ///   A strongly-typed resource class, for looking up localized strings, etc.
    /// </summary>
    // This class was auto-generated by the StronglyTypedResourceBuilder
    // class via a tool like ResGen or Visual Studio.
    // To add or remove a member, edit your .ResX file then rerun ResGen
    // with the /str option, or rebuild your VS project.
    [global::System.CodeDom.Compiler.GeneratedCodeAttribute("System.Resources.Tools.StronglyTypedResourceBuilder", "4.0.0.0")]
    [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
    [global::System.Runtime.CompilerServices.CompilerGeneratedAttribute()]
    internal class Resources {
        
        private static global::System.Resources.ResourceManager resourceMan;
        
        private static global::System.Globalization.CultureInfo resourceCulture;
        
        [global::System.Diagnostics.CodeAnalysis.SuppressMessageAttribute("Microsoft.Performance", "CA1811:AvoidUncalledPrivateCode")]
        internal Resources() {
        }
        
        /// <summary>
        ///   Returns the cached ResourceManager instance used by this class.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        internal static global::System.Resources.ResourceManager ResourceManager {
            get {
                if (object.ReferenceEquals(resourceMan, null)) {
                    global::System.Resources.ResourceManager temp = new global::System.Resources.ResourceManager("SSHTunnelManagerGUI.Properties.Resources", typeof(Resources).Assembly);
                    resourceMan = temp;
                }
                return resourceMan;
            }
        }
        
        /// <summary>
        ///   Overrides the current thread's CurrentUICulture property for all
        ///   resource lookups using this strongly typed resource class.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        internal static global::System.Globalization.CultureInfo Culture {
            get {
                return resourceCulture;
            }
            set {
                resourceCulture = value;
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to About {0}.
        /// </summary>
        internal static string AboutBox_AboutText {
            get {
                return ResourceManager.GetString("AboutBox_AboutText", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Version {0}.
        /// </summary>
        internal static string AboutBox_VersionText {
            get {
                return ResourceManager.GetString("AboutBox_VersionText", resourceCulture);
            }
        }
        
        internal static System.Drawing.Bitmap arrow_circle_315 {
            get {
                object obj = ResourceManager.GetObject("arrow_circle_315", resourceCulture);
                return ((System.Drawing.Bitmap)(obj));
            }
        }
        
        internal static System.Drawing.Bitmap arrow_skip_090 {
            get {
                object obj = ResourceManager.GetObject("arrow_skip_090", resourceCulture);
                return ((System.Drawing.Bitmap)(obj));
            }
        }
        
        internal static System.Drawing.Bitmap arrow_skip_270 {
            get {
                object obj = ResourceManager.GetObject("arrow_skip_270", resourceCulture);
                return ((System.Drawing.Bitmap)(obj));
            }
        }
        
        internal static System.Drawing.Bitmap brightness {
            get {
                object obj = ResourceManager.GetObject("brightness", resourceCulture);
                return ((System.Drawing.Bitmap)(obj));
            }
        }
        
        internal static System.Drawing.Bitmap brightness_small {
            get {
                object obj = ResourceManager.GetObject("brightness_small", resourceCulture);
                return ((System.Drawing.Bitmap)(obj));
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Close.
        /// </summary>
        internal static string ButtonText_Close {
            get {
                return ResourceManager.GetString("ButtonText_Close", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to http://creativecommons.org/licenses/by/3.0/.
        /// </summary>
        internal static string CCA3LicensePage {
            get {
                return ResourceManager.GetString("CCA3LicensePage", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to &amp;Edit....
        /// </summary>
        internal static string ContextMenuText_Edit {
            get {
                return ResourceManager.GetString("ContextMenuText_Edit", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to &amp;Remove.
        /// </summary>
        internal static string ContextMenuText_Remove {
            get {
                return ResourceManager.GetString("ContextMenuText_Remove", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Start.
        /// </summary>
        internal static string ContextMenuText_Start {
            get {
                return ResourceManager.GetString("ContextMenuText_Start", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Start FileZilla SFTP.
        /// </summary>
        internal static string ContextMenuText_StartFileZilla {
            get {
                return ResourceManager.GetString("ContextMenuText_StartFileZilla", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Start psftp.
        /// </summary>
        internal static string ContextMenuText_StartPsftp {
            get {
                return ResourceManager.GetString("ContextMenuText_StartPsftp", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Start PuTTY.
        /// </summary>
        internal static string ContextMenuText_StartPuTTY {
            get {
                return ResourceManager.GetString("ContextMenuText_StartPuTTY", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Stop.
        /// </summary>
        internal static string ContextMenuText_Stop {
            get {
                return ResourceManager.GetString("ContextMenuText_Stop", resourceCulture);
            }
        }
        
        internal static System.Drawing.Bitmap control {
            get {
                object obj = ResourceManager.GetObject("control", resourceCulture);
                return ((System.Drawing.Bitmap)(obj));
            }
        }
        
        internal static System.Drawing.Bitmap control_000_small {
            get {
                object obj = ResourceManager.GetObject("control_000_small", resourceCulture);
                return ((System.Drawing.Bitmap)(obj));
            }
        }
        
        internal static System.Drawing.Bitmap control_stop_square {
            get {
                object obj = ResourceManager.GetObject("control_stop_square", resourceCulture);
                return ((System.Drawing.Bitmap)(obj));
            }
        }
        
        internal static System.Drawing.Bitmap control_stop_square_small {
            get {
                object obj = ResourceManager.GetObject("control_stop_square_small", resourceCulture);
                return ((System.Drawing.Bitmap)(obj));
            }
        }
        
        internal static System.Drawing.Bitmap database {
            get {
                object obj = ResourceManager.GetObject("database", resourceCulture);
                return ((System.Drawing.Bitmap)(obj));
            }
        }
        
        internal static System.Drawing.Bitmap databases__arrow {
            get {
                object obj = ResourceManager.GetObject("databases__arrow", resourceCulture);
                return ((System.Drawing.Bitmap)(obj));
            }
        }
        
        internal static System.Drawing.Bitmap disco {
            get {
                object obj = ResourceManager.GetObject("disco", resourceCulture);
                return ((System.Drawing.Bitmap)(obj));
            }
        }
        
        internal static System.Drawing.Bitmap disk {
            get {
                object obj = ResourceManager.GetObject("disk", resourceCulture);
                return ((System.Drawing.Bitmap)(obj));
            }
        }
        
        internal static System.Drawing.Bitmap exclamation_small {
            get {
                object obj = ResourceManager.GetObject("exclamation_small", resourceCulture);
                return ((System.Drawing.Bitmap)(obj));
            }
        }
        
        internal static System.Drawing.Bitmap filezilla {
            get {
                object obj = ResourceManager.GetObject("filezilla", resourceCulture);
                return ((System.Drawing.Bitmap)(obj));
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to http://p.yusukekamiyamane.com/.
        /// </summary>
        internal static string FuguePage {
            get {
                return ResourceManager.GetString("FuguePage", resourceCulture);
            }
        }
        
        internal static System.Drawing.Bitmap Gear {
            get {
                object obj = ResourceManager.GetObject("Gear", resourceCulture);
                return ((System.Drawing.Bitmap)(obj));
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to http://www.gnu.org/licenses/gpl.html.
        /// </summary>
        internal static string GNUGPLv3Page {
            get {
                return ResourceManager.GetString("GNUGPLv3Page", resourceCulture);
            }
        }
        
        internal static System.Drawing.Bitmap greenCircle {
            get {
                object obj = ResourceManager.GetObject("greenCircle", resourceCulture);
                return ((System.Drawing.Bitmap)(obj));
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Add New Host - SSH Tunnel Manager.
        /// </summary>
        internal static string HostDialog_AddNewHostTitle {
            get {
                return ResourceManager.GetString("HostDialog_AddNewHostTitle", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to You may forget to press &apos;Add&apos; button, add new tunnel into list before continue?.
        /// </summary>
        internal static string HostDialog_AddTunnelButtonReminder {
            get {
                return ResourceManager.GetString("HostDialog_AddTunnelButtonReminder", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to None.
        /// </summary>
        internal static string HostDialog_DependsOnNone {
            get {
                return ResourceManager.GetString("HostDialog_DependsOnNone", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Edit Host - SSH Tunnel Manager.
        /// </summary>
        internal static string HostDialog_EditHostTitle {
            get {
                return ResourceManager.GetString("HostDialog_EditHostTitle", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Host property is null..
        /// </summary>
        internal static string HostDialog_HostPropertyIsNull {
            get {
                return ResourceManager.GetString("HostDialog_HostPropertyIsNull", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Recently added: {0}.
        /// </summary>
        internal static string HostDialog_RecentlyAdded {
            get {
                return ResourceManager.GetString("HostDialog_RecentlyAdded", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Status {0} not supported..
        /// </summary>
        internal static string HostViewModel_StatusNotSupported {
            get {
                return ResourceManager.GetString("HostViewModel_StatusNotSupported", resourceCulture);
            }
        }
        
        internal static System.Drawing.Bitmap icon_16x16_putty {
            get {
                object obj = ResourceManager.GetObject("icon_16x16_putty", resourceCulture);
                return ((System.Drawing.Bitmap)(obj));
            }
        }
        
        internal static System.Drawing.Bitmap key__arrow {
            get {
                object obj = ResourceManager.GetObject("key__arrow", resourceCulture);
                return ((System.Drawing.Bitmap)(obj));
            }
        }
        
        internal static System.Drawing.Bitmap logo_putty {
            get {
                object obj = ResourceManager.GetObject("logo_putty", resourceCulture);
                return ((System.Drawing.Bitmap)(obj));
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Storage was modified, save before closing?.
        /// </summary>
        internal static string MessageBoxText_AskForSaveStorage {
            get {
                return ResourceManager.GetString("MessageBoxText_AskForSaveStorage", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Are you sure you want to remove host &apos;{0}&apos;?.
        /// </summary>
        internal static string MessageBoxText_RemoveHostAsk {
            get {
                return ResourceManager.GetString("MessageBoxText_RemoveHostAsk", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Following hosts depends on host &apos;{0}&apos;:{1}{1}{2}{1}{1}Are you sure you want to remove the selected host?.
        /// </summary>
        internal static string MessageBoxText_RemoveHostAsk2 {
            get {
                return ResourceManager.GetString("MessageBoxText_RemoveHostAsk2", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Some hosts what host &apos;{0}&apos; depends on are down. Start recursively?.
        /// </summary>
        internal static string MessageBoxText_StartHostRecursively {
            get {
                return ResourceManager.GetString("MessageBoxText_StartHostRecursively", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to http://www.chiark.greenend.org.uk/~sgtatham/putty/licence.html.
        /// </summary>
        internal static string MITLicensePage {
            get {
                return ResourceManager.GetString("MITLicensePage", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to This control is not registered new-password/confirmation control..
        /// </summary>
        internal static string NewPasswordValidatorFunctor_Validate_InvalidControl {
            get {
                return ResourceManager.GetString("NewPasswordValidatorFunctor_Validate_InvalidControl", resourceCulture);
            }
        }
        
        internal static System.Drawing.Bitmap orangeCircle {
            get {
                object obj = ResourceManager.GetObject("orangeCircle", resourceCulture);
                return ((System.Drawing.Bitmap)(obj));
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to http://code.google.com/p/ssh-tunnel-manager/.
        /// </summary>
        internal static string ProjectPage {
            get {
                return ResourceManager.GetString("ProjectPage", resourceCulture);
            }
        }
        
        internal static System.Drawing.Icon psftp {
            get {
                object obj = ResourceManager.GetObject("psftp", resourceCulture);
                return ((System.Drawing.Icon)(obj));
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to START action for host &apos;{0}&apos; timed out. Terminating actions chain..
        /// </summary>
        internal static string PuttyLink_WaitForStartTimedOut {
            get {
                return ResourceManager.GetString("PuttyLink_WaitForStartTimedOut", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to STOP action for host &apos;{0}&apos; timed out. Terminating actions chain..
        /// </summary>
        internal static string PuttyLink_WaitForStopTimedOut {
            get {
                return ResourceManager.GetString("PuttyLink_WaitForStopTimedOut", resourceCulture);
            }
        }
        
        internal static System.Drawing.Bitmap redCircle {
            get {
                object obj = ResourceManager.GetObject("redCircle", resourceCulture);
                return ((System.Drawing.Bitmap)(obj));
            }
        }
        
        internal static System.Drawing.Bitmap Remote_desktop_connection_icon16 {
            get {
                object obj = ResourceManager.GetObject("Remote_desktop_connection_icon16", resourceCulture);
                return ((System.Drawing.Bitmap)(obj));
            }
        }
        
        internal static System.Drawing.Bitmap server__minus {
            get {
                object obj = ResourceManager.GetObject("server__minus", resourceCulture);
                return ((System.Drawing.Bitmap)(obj));
            }
        }
        
        internal static System.Drawing.Bitmap server__pencil {
            get {
                object obj = ResourceManager.GetObject("server__pencil", resourceCulture);
                return ((System.Drawing.Bitmap)(obj));
            }
        }
        
        internal static System.Drawing.Bitmap server__plus {
            get {
                object obj = ResourceManager.GetObject("server__plus", resourceCulture);
                return ((System.Drawing.Bitmap)(obj));
            }
        }
        
        internal static System.Drawing.Bitmap server_down {
            get {
                object obj = ResourceManager.GetObject("server_down", resourceCulture);
                return ((System.Drawing.Bitmap)(obj));
            }
        }
        
        internal static System.Drawing.Bitmap server_up {
            get {
                object obj = ResourceManager.GetObject("server_up", resourceCulture);
                return ((System.Drawing.Bitmap)(obj));
            }
        }
        
        internal static System.Drawing.Bitmap server_up_warnings {
            get {
                object obj = ResourceManager.GetObject("server_up_warnings", resourceCulture);
                return ((System.Drawing.Bitmap)(obj));
            }
        }
        
        internal static System.Drawing.Bitmap ServerImage {
            get {
                object obj = ResourceManager.GetObject("ServerImage", resourceCulture);
                return ((System.Drawing.Bitmap)(obj));
            }
        }
        
        internal static System.Drawing.Bitmap Servers {
            get {
                object obj = ResourceManager.GetObject("Servers", resourceCulture);
                return ((System.Drawing.Bitmap)(obj));
            }
        }
        
        internal static System.Drawing.Bitmap servers__minus {
            get {
                object obj = ResourceManager.GetObject("servers__minus", resourceCulture);
                return ((System.Drawing.Bitmap)(obj));
            }
        }
        
        internal static System.Drawing.Bitmap tick_circle {
            get {
                object obj = ResourceManager.GetObject("tick_circle", resourceCulture);
                return ((System.Drawing.Bitmap)(obj));
            }
        }
        
        internal static System.Drawing.Bitmap tick_small_circle {
            get {
                object obj = ResourceManager.GetObject("tick_small_circle", resourceCulture);
                return ((System.Drawing.Bitmap)(obj));
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to &amp;Exit.
        /// </summary>
        internal static string TrayForm_ContextMenu_Exit {
            get {
                return ResourceManager.GetString("TrayForm_ContextMenu_Exit", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Hide/show.
        /// </summary>
        internal static string TrayForm_ContextMenu_HideShow {
            get {
                return ResourceManager.GetString("TrayForm_ContextMenu_HideShow", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to {0} has minimized here..
        /// </summary>
        internal static string TrayForm_OnMinimizedText {
            get {
                return ResourceManager.GetString("TrayForm_OnMinimizedText", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Control has not been set..
        /// </summary>
        internal static string Validator_ValidateControl_ControlHasNotBeenSet {
            get {
                return ResourceManager.GetString("Validator_ValidateControl_ControlHasNotBeenSet", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to File does not exist..
        /// </summary>
        internal static string ValidatorError_FileDoesNotExist {
            get {
                return ResourceManager.GetString("ValidatorError_FileDoesNotExist", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Alias is busy by another host..
        /// </summary>
        internal static string ValidatorError_HostAliasBusy {
            get {
                return ResourceManager.GetString("ValidatorError_HostAliasBusy", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Invalid hostname.
        /// </summary>
        internal static string ValidatorError_Hostname {
            get {
                return ResourceManager.GetString("ValidatorError_Hostname", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to You need to specify hostname in the form &apos;hostname:port&apos;.
        /// </summary>
        internal static string ValidatorError_HostnameAndPort {
            get {
                return ResourceManager.GetString("ValidatorError_HostnameAndPort", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Local port is busy by another tunnel in host &apos;{0}&apos;..
        /// </summary>
        internal static string ValidatorError_LocalPortBusyAnotherHost {
            get {
                return ResourceManager.GetString("ValidatorError_LocalPortBusyAnotherHost", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Local port is busy by another tunnel of this host..
        /// </summary>
        internal static string ValidatorError_LocalPortBusyThisHost {
            get {
                return ResourceManager.GetString("ValidatorError_LocalPortBusyThisHost", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Password and confirmation does not match..
        /// </summary>
        internal static string ValidatorError_NewPassword {
            get {
                return ResourceManager.GetString("ValidatorError_NewPassword", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to You need to specify this value..
        /// </summary>
        internal static string ValidatorError_NotNullOrWhitespaces {
            get {
                return ResourceManager.GetString("ValidatorError_NotNullOrWhitespaces", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to The value should be a word without spaces..
        /// </summary>
        internal static string ValidatorError_OnlyOneWord {
            get {
                return ResourceManager.GetString("ValidatorError_OnlyOneWord", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to You need to specify port number as number in range 1-65536.
        /// </summary>
        internal static string ValidatorError_PortNumber {
            get {
                return ResourceManager.GetString("ValidatorError_PortNumber", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Alias is busy by another tunnel..
        /// </summary>
        internal static string ValidatorError_TunnelAliasBusy {
            get {
                return ResourceManager.GetString("ValidatorError_TunnelAliasBusy", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Destination hostname should be empty for dynamic tunnels..
        /// </summary>
        internal static string ValidatorError_TunnelDstHostnameNotEmpty {
            get {
                return ResourceManager.GetString("ValidatorError_TunnelDstHostnameNotEmpty", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Hostname should be empty for dynamic tunnels..
        /// </summary>
        internal static string ValidatorError_TunnelHostnameNotEmpty {
            get {
                return ResourceManager.GetString("ValidatorError_TunnelHostnameNotEmpty", resourceCulture);
            }
        }
        
        internal static System.Drawing.Bitmap yellowCircle {
            get {
                object obj = ResourceManager.GetObject("yellowCircle", resourceCulture);
                return ((System.Drawing.Bitmap)(obj));
            }
        }
    }
}
